name: Detect new Flutter release
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  detect:
    name: Detect new Flutter release
    runs-on: ubuntu-latest
    steps:
      - run: echo 'TODO'