name: Push Docker images
on:
  push:
    branches:
      - master
jobs:
  push_images:
    name: Push images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh build_docker.sh
      - run: sh push_docker.sh